version: '3.8'

services:
  master:
    image: openjdk:8-jdk
    container_name: mastermachine
    restart: always
    ports:
      - 9870:9870
      - 8088:8088

    networks:
      - hadoopnetwork
    command: tail -f /dev/null

  slave1:
    image: openjdk:8-jdk
    container_name: slave1machine
    restart: always
    ports:
      - 9864:9864
      - 8042:8042

    networks:
      - hadoopnetwork

    command: tail -f /dev/null

  slave2:
    image: openjdk:8-jdk
    container_name: slave2machine
    restart: always
    networks:
      - hadoopnetwork
    command: tail -f /dev/null
    

  slave3:
    image: openjdk:8-jdk
    container_name: slave3machine
    restart: always
    networks:
      - hadoopnetwork
    command: tail -f /dev/null


networks:
  hadoopnetwork:
    name: hadoopnetwork
    driver: bridge
    


